export const POINTER_DOWN = 'pointerdown'
export const POINTER_MOVE = 'pointermove'
export const POINTER_UP = 'pointerup'
export const POINTER_LEAVE = 'pointerleave'
export const POINTER_CANCEL = 'pointercancel'
export const VISIBILITY_CHANGE = 'visibilitychange'
